name: family_finance
description: Simple personal finance app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
